version: '3.4'
services:
  app:
    build: .
    container_name: 'timeoff_app'
    restart: unless-stopped
    env_file: .env        
    volumes:
      - ./volumes/config:/opt/timeoff-management/config
      - ./volumes/db:/opt/timeoff-management/db
    expose:
    - "3000"
  proxy:
    image: nginx:1.15-alpine
    container_name: 'timeoff_proxy'
    restart: unless-stopped
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./ssl:/etc/nginx/ssl:ro
    depends_on:
    - app
    ports:
    - 80:80
    - 443:443
    links:
    - app:app
